// <auto-generated />
namespace PatientsDataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedsmokerdiabeteshdlldl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedsmokerdiabeteshdlldl));
        
        string IMigrationMetadata.Id
        {
            get { return "201705310628416_added smoker, diabetes, hdl, ldl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
