// <auto-generated />
namespace PatientsDataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reworkingmedlist2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reworkingmedlist2));
        
        string IMigrationMetadata.Id
        {
            get { return "201705120859512_reworking med list2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
